receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: "otel-collector"
          static_configs:
            - targets: ["localhost:8888"]
              labels:
                job_name: otel-collector
        - job_name: "rabbitmq"
          static_configs:
            - targets: ["103.118.21.227:15692"]

  filelog/general-services:
    include: [/logs/general-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: general-services

  filelog/trustgate-services:
    include: [/logs/trustgate-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: trustgate-services

  filelog/scheduler-services:
    include: [/logs/scheduler-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: scheduler-services

  filelog/odoo:
    include: [/logs/odoo-log/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: odoo

  filelog/notification-services:
    include: [/logs/notification-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: notification-services

  filelog/loan-services:
    include: [/logs/loan-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: loan-services

  filelog/experian-services:
    include: [/logs/experian-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: experian-services

  filelog/application-services:
    include: [/logs/application-services/*.log]
    start_at: beginning
    include_file_path: true
    attributes:
      service.name: application-services

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      filesystem: {}
      load: {}
      network: {}
      processes: {}

processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
  signozspanmetrics/delta:
    metrics_exporter: signozclickhousemetrics
    metrics_flush_interval: 60s
    latency_histogram_buckets:
      [
        100us,
        1ms,
        2ms,
        6ms,
        10ms,
        50ms,
        100ms,
        250ms,
        500ms,
        1000ms,
        1400ms,
        2000ms,
        5s,
        10s,
        20s,
        40s,
        60s,
      ]
    dimensions_cache_size: 100000
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    enable_exp_histogram: true
    dimensions:
      - name: service.namespace
        default: default
      - name: deployment.environment
        default: default
      - name: signoz.collector.id
      - name: service.version
      - name: browser.platform
      - name: browser.mobile
      - name: k8s.cluster.name
      - name: k8s.node.name
      - name: k8s.namespace.name
      - name: host.name
      - name: host.type
      - name: container.name

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777

exporters:
  clickhousetraces:
    datasource: tcp://clickhouse:9000/signoz_traces
    low_cardinal_exception_grouping: ${env:LOW_CARDINAL_EXCEPTION_GROUPING}
    use_new_schema: true
  signozclickhousemetrics:
    dsn: tcp://clickhouse:9000/signoz_metrics
  clickhouselogsexporter:
    dsn: tcp://clickhouse:9000/signoz_logs
    timeout: 10s
    use_new_schema: true

service:
  telemetry:
    logs:
      encoding: json
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [signozspanmetrics/delta, batch]
      exporters: [clickhousetraces]

    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [signozclickhousemetrics]

    metrics/prometheus:
      receivers: [prometheus]
      processors: [batch]
      exporters: [signozclickhousemetrics]

    logs:
      receivers:
        [
          otlp,
          filelog/general-services,
          filelog/trustgate-services,
          filelog/scheduler-services,
          filelog/odoo,
          filelog/notification-services,
          filelog/loan-services,
          filelog/experian-services,
          filelog/application-services,
        ]
      processors: [batch]
      exporters: [clickhouselogsexporter]
